### PR TITLE
Add the shell prompt/command to custom-errors.sh

### PR DESCRIPTION
**Pull request by johnd**
The shell entry for custom-errors is missing the shell prompt line. Small change, but nice for consistency!

### CODE REVIEW

**Comment by johnd** [comment]
I had completely missed it there despite working through the examples back-to-back! I've added it in there and double checked all the other examples and they all seem to be fine.

**Review by eliben — APPROVED** [review]
Thanks!

**Comment by EmNudge** [comment]
In both these examples, shouldn't the prompt be `custom-errors.go` and not `custom-errors.sh`?

**Comment by eliben** [comment]
> In both these examples, shouldn't the prompt be `custom-errors.go` and not `custom-errors.sh`?

Good catch! Would you like to send a PR to fix this?

**Pull request merged**
