### PR TITLE
Fix a typo

### PR DESCRIPTION
**Pull request by yurivish**

### CODE REVIEW

**Comment by mmcgrana** [comment]
Thanks!

**Review by eliben — APPROVED** [review]

**Comment by mmcgrana** [comment]
Hmm I merged this but GitHub didn't pick it up here: https://github.com/mmcgrana/gobyexample/commit/b76ff6c4134d068480e3be7860371d70ecd9d37e. Anyways thanks!

**Comment by eliben** [comment]
> Hmm I merged this but GitHub didn't pick it up here: [b76ff6c](https://github.com/mmcgrana/gobyexample/commit/b76ff6c4134d068480e3be7860371d70ecd9d37e). Anyways thanks!

Mark, I recommend merging using the GitHub UI on Pull Request pages. When a PR is approved and the tests pass you have an option to "Squash and merge". This:

1. Avoids annoying "merge" commits
2. Squashes all temporary commits folks make during working on a PR into a single commit
3. Automatically closes the PR

**Comment by mmcgrana** [comment]
@eliben OK noted thanks, will give that flow a try!

**Pull request closed without merging**
