### PR TITLE
Error checking in examples/writing-files

### PR DESCRIPTION
**Pull request by calmh**
This corrects and comments a number of small issues around the error
checking in this example.

### CODE REVIEW

**Comment by muyiwaolurin** [comment]
Hi @calmh,  It might be leave ```defer f.Close()``` after opening a file. Its one of the Golang ways

**Comment by calmh** [comment]
No. Not when writing to a file. The error checking in this example is frankly embarrassing, but I think this project has been abandoned.

**Comment by muyiwaolurin** [comment]
wow!! I didn't know that. Thanks @calmh

**Comment by calmh** [comment]
`¯\_(ツ)_/¯`

**Pull request closed without merging**
