### PR TITLE
Added more information about shorthand variable declaration

### PR DESCRIPTION
**Pull request by grejojoby**
Have added information on shorthand variable declaration as per requested in the following issue.
Issue: #438

### CODE REVIEW

**Review by eliben — COMMENTED** [review]
I think I've just reviewed this in #455 ?

**Comment by eliben** [comment]
Can you address the review comments from #455?

**Comment by grejojoby** [comment]
> Can you address the review comments from #455?

Actually I wanted to keep the declaration outside of the main function to depict it better that I'm speaking of declaration of variable with shorthand notation outside of the function.

**Review by eliben — APPROVED** [review]

**Review by jadequeen93 — COMMENTED** [review]
Good

**Pull request merged**
