### PR TITLE
Remove unreachable code from enums example

### PR DESCRIPTION
**Pull request by BigJayToDaIzo**
After confirming I did not misunderstand how switch default and panic works, I realized there was some unreachable code in the example that may confuse new learners.  Go LSP confirms.

image

### CODE REVIEW

**Review by eliben — APPROVED** [review]
Thanks, this makes sense!

**Comment by BigJayToDaIzo** [comment]
> Thanks, this makes sense!

My pleasure!  Thank YOU for the lovely refresher course after not having looked at any Go for a month! :grin:

**Comment by BigJayToDaIzo** [comment]
woops, fat fingered the mouse on that early close before merge.  Apologies!

**Comment by eliben** [comment]
> woops, fat fingered the mouse on that early close before merge. Apologies!

No worries, it's merged now.

Note that it may take a few days to show up on the published website, since the upload is done manually.

**Pull request merged**
